-- This file is no longer used. pgstore now applies its schema via a
-- real migration runner -- see migrations/*.sql and migrate.go. Kept
-- only as a pointer in case anything on disk still references the old
-- filename; safe to delete.
