################################################################################
# @file         ingress.yaml
# @brief        Part of the Muster templates module.
# @project      Muster
#
# @author       Michael McGinnis
# @date         2026-09-17
# @version      1.0.0
#
# Copyright (c) 2026 McGinnis Technologies, LLC. All rights reserved.
# Licensed under the MIT License -- see the LICENSE file at the repository root.
################################################################################

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "muster.fullname" . }}-api
  labels:
    {{- include "muster.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "muster.fullname" . }}-api
                port:
                  number: {{ .Values.server.apiPort }}
{{- end }}
